@server=http://localhost:4004
@username=alice
@password=


### Wallets
# @name Wallets_GET
GET {{server}}/Main/Wallets?$expand=customer
Authorization: Basic {{username}}:{{password}}

### Parameters
# @name Parameters_GET
GET {{server}}/Main/getParameters()
Authorization: Basic {{username}}:{{password}}

### Parameters
# @name Parameters_PATCH
POST {{server}}/Main/updateParameters
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
    "parameters" : {
        "is_cashback_active": true,
        "cashback_return": "20.5",
        "cashback_redemption_limit": "20"
    }
}


